language: go

before_install:
- go get github.com/schrej/godacov

go:
- "1.14"

env:
- GO111MODULE=on

script:
#- $GOPATH/bin/goveralls -service=travis-ci
- go test ./... -cover -coverprofile=./coverage.out
- godacov -t $CODACY_TOKEN -r ./coverage.out -c $TRAVIS_COMMIT
