language: go

before_install:
- go get github.com/mattn/goveralls

go:
- 1.12

env:
- GO111MODULE=on

script:
#- $GOPATH/bin/goveralls -service=travis-ci
- go test ./... -cover -coverprofile=./coverage.out
- godacov -t $CODACY_TOKEN -r ./coverage.out -c $TRAVIS_COMMIT
